version: '3'
services:
  web:
    build: ./server
    working_dir: /app
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
    depends_on:
      - db
      - mq
    command: python main.py
    networks:
      - net
  email:
    build: ./email
    working_dir: /app
    volumes:
      - ./email:/app
    depends_on:
      - mq
    command: python main.py
    networks:
      - net
  spider:
    build: ./spider
    working_dir: /app
    volumes:
      - ./spider:/app
    depends_on:
      - db
    command: 'scrapy crawl news'
    networks:
      - net
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - net
  mq:
    image: rabbitmq:latest
    networks:
      - net
networks:
  net:
