version: '3'
services:
  web:
    build: ./server
    working_dir: /app
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
    depends_on:
      - db
      - mq
    command: python main.py
  email:
    build: ./email
    working_dir: /app
    volumes:
      - ./email:/app
    depends_on:
      - mq
    command: python main.py
  spider:
    build: ./spider
    working_dir: /app
    volumes:
      - ./spider:/app
    depends_on:
      - db
    command: 'scrapy crawl news'
  db:
    image: mongo:latest
  mq:
    image: rabbitmq:latest
